### ISSUE TITLE
Can you provide the data needed for analysis in the R code?

### ISSUE THREAD

**Issue by maozhitao** [zelezniak-lab/kinase_metabolism#1]
I am not very clear about the specific organization of these data, so I can't use these codes.

just like the following data that needs to be loaded:
load("../../R/objects/proteins.matrix.sva.0.5.1.RData")
load("../../R/objects/proteins.matrix.sva.0.5.1.FC.RData")
load("../../R/objects/iMM904._load_.RData")
load("../../R/objects/exp_metadata._clean_.RData")

**Comment by alzel** [comment]
Sorry for this, i still didn’t finish with it, will fix it asap..

**Comment by alzel** [comment]
Please see the data and code is now uploaded
